#pylint: disable=missing-docstring, invalid-name, line-too-long, attribute-defined-outside-init
from accounts.models import Token
from django.test import TestCase
from django.contrib import auth
User = auth.get_user_model()


class UserModelTest(TestCase):

    def test__user_model__when_created__user_is_valid_with_email_only(self):
        user = User(email='foo@bar.com')
        user.full_clean()  # should not raise


    def test__user_model__when_created__has_email_as_primary_key(self):
        user = User(email='foo@bar.com')

        self.assertEqual(user.pk, 'foo@bar.com')


    def test__user_model__when_authenticating__can_login(self):
        user = User.objects.create(email='edith@example.com')
        user.backend = ''
        request = self.client.request().wsgi_request
        auth.login(request, user) # should not raise


class TokenModelTest(TestCase):

    def test__token_model__when_created__links_user_with_autogenerated_uid(self):
        token1 = Token.objects.create(email='foo@foo.com')
        token2 = Token.objects.create(email='bar@bar.com')

        self.assertNotEqual(token1.uid, token2.uid)
