from accounts.models import Token
from django.test import TestCase
from django.contrib.auth import get_user_model

User = get_user_model()


class UserModelTest(TestCase):

    def test__user_model__when_created__user_is_valid_with_email_only(self):
        user = User(email='foo@bar.com')
        user.full_clean()  # should not raise

    def test__user_model__when_created__has_email_as_primary_key(self):
        user = User(email='foo@bar.com')

        self.assertEqual(user.pk, 'foo@bar.com')


class TokenModelTest(TestCase):

    def test__token_model__when_created__links_user_with_autogenerated_uid(self):
        token1 = Token.objects.create(email='foo@foo.com')
        token2 = Token.objects.create(email='bar@bar.com')

        self.assertNotEqual(token1.uid, token2.uid)
